### ISSUE TITLE
No controls available including video progress bar

### ISSUE THREAD

**Issue by dakeashish1997** [mafanwei/libvlc#1]
I checked this library and its very useful to play live videos. But progress bar is not given for video surface. also, controls like play, pause, next, previous and seek should be given in library. It will be more beneficial to users. Try to implement it if possible. Waiting for reply.

**Comment by mafanwei** [comment]
Yes, that does seem to be a problem.
What I was thinking at the time was that streaming doesn't need a controller.
Can you help me improve it?

**Comment by dakeashish1997** [comment]
Ya sure. I am checking the code. But you implemented external API in project module and then just created a wrapper around it, so it will be some difficult.

**Comment by mafanwei** [comment]
You can choose to refactor the code, and there shouldn't be anyone using it right now, except me, of course.
I think you can use the ‘player’ in it to do everything.

**Comment by dakeashish1997** [comment]
OK
